### ISSUE TITLE
the firmware can't be identified by MI-Walkie-Talkie-Plus v1.1

### ISSUE THREAD

**Issue by huzheyi** [Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware#1]
**Thank you so much for your effort first!**

I installed the v1.1 apk and followed your instructions, while the firmware updating stucked at 0%. 

My device is XMDJJ02 produced on April 2021. Maybe the hardware version(4.5) is too new to fit the firmware.

I thought I could do that reverse-engineering as you mentioned with IDA, but I don't know how to get the original firmware.

Below is my screenshots:

![91648543765_ pic](https://user-images.githubusercontent.com/8382132/160572983-c2bf140b-3c52-487e-9b00-dcca702c7a27.jpg)

![81648543748_ pic](https://user-images.githubusercontent.com/8382132/160572969-a4729492-86bb-4c61-998a-0d1768dfe285.jpg)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> **Thank you so much for your effort first!**
> 
> I installed the v1.1 apk and followed your instructions, while the firmware updating stucked at 0%.
> 
> My device is XMDJJ02 produced on April 2021. Maybe the hardware version(4.5) is too new to fit the firmware.
> 

It looks like Mi PTT+ does not have an access to the walki-talkie firmware file on your phone : normally, there should be "Flash 'shark_1.0.5-mod-nlt_hw8.bin'" text on the button, instead of the standard "Start updating". The problem is, in case you have Android 11+ on the phone, you should manually give the file system access permission to Mi PTT+; to do this, long-click MI PTT+ icon, then click "App info" --> "Permissions" --> "Storage" and check "Allow management of all files" mark.

**Comment by huzheyi** [comment]
> > **Thank you so much for your effort first!**
> > I installed the v1.1 apk and followed your instructions, while the firmware updating stucked at 0%.
> > My device is XMDJJ02 produced on April 2021. Maybe the hardware version(4.5) is too new to fit the firmware.
> 
> It looks like Mi PTT+ does not have an access to the walki-talkie firmware file on your phone : normally, there should be "Flash 'shark_1.0.5-mod-nlt_hw8.bin'" text on the button, instead of the standard "Start updating". The problem is, in case you have Android 11+ on the phone, you should manually give the file system access permission to Mi PTT+; to do this, long-click MI PTT+ icon, then click "App info" --> "Permissions" --> "Storage" and check "Allow management of all files" mark.

Thank you for your reply.

I've authorized all permissions to Mi PTT+, and tried several android devices, the results are the same. So I doubt the hardware version caused this issue, maybe the firmware does not fit my hardware.

So I wonder if you could teach me to export my firmware from my XMDJJ02, then I make a reverse-engineering with IDA.

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> Thank you for your reply.
> 
> I've authorized all permissions to Mi PTT+, and tried several android devices, the results are the same. So I doubt the hardware version caused this issue, maybe the firmware does not fit my hardware.
> 
You are right, i'm sorry for my inattentiveness. The problem is, you have the walkie-talkie hardware revision 5 ("Hardware version 4.5" according to your screenshot), but my firmware mod is for hardware revision 8 (Reported by Mi PTT+ as "Hardware version 4.8"). There is nothing unusual about this, all the previous Xiaomi walkie-talkies have several hardware revisions.

> So I wonder if you could teach me to export my firmware from my XMDJJ02, then I make a reverse-engineering with IDA.
> 
You will need in soldering iron, any USB-UART adapter with 3.3v output, PC with terminal software (I suggest Tera Term : https://ttssh2.osdn.jp/index.html.en)... and the right hands :). Are you ready?

**Comment by huzheyi** [comment]
> You will need in soldering iron, any USB-UART adapter with 3.3v output, PC with terminal software (I suggest Tera Term : https://ttssh2.osdn.jp/index.html.en)... and the right hands :). Are you ready?

Sounds like not that easy as I thought. So you mean I should disassemble my walkie-talkie, and set up a serial communication with a USB-UART adapter, then export the firmware using command, right?
I noticed that you said we could revert to the official firmware by creating the empty "Mi-walkie-talkie.firmware" folder, So I guess maybe there is a way to fetch the official firmware downloaded by the Mi PTT+.

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> I noticed that you said we could revert to the official firmware by creating the empty "Mi-walkie-talkie.firmware" folder, So I guess maybe there is a way to fetch the official firmware downloaded by the Mi PTT+.
>
This method works for all the previous models, but not for for XMDJJ02 ! It looks like the walkie-talkie developers are trying to struggle against firmware modding, so they are not publish new firmware on the official site.

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> Sounds like not that easy as I thought. So you mean I should disassemble my walkie-talkie, and set up a serial communication with a USB-UART adapter, then export the firmware using command, right?
>
Fortunately, it is not necessary to disassemble the walkie-talkie, because "USB" connector on Mi 1S and Mi 2 models is actually not a USB, but a 3.3v UART ! So you need in a soldering iron to prepare such a "convertor" :
![USB](https://user-images.githubusercontent.com/57772603/164699755-549072e5-3395-41a7-8095-0cad848e4609.JPG)
Then, connect it to USB-UART adapter by the following way :
BLACK wire (common) - to GND
GREEN wire (D+) - to TxD
WHITE wire (D-) - to RxD
RED wire (+5v) - not connected
![USB_UART](https://user-images.githubusercontent.com/57772603/164700745-de9d8c47-9293-4381-ada8-a58c448b03cf.JPG)

**Comment by miheico** [comment]
Hi, thanks for redirecting me to this branch. Is there any firmware for the 5th hardware version radio? Or is there any way to make it at least English?

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> Hi, thanks for redirecting me to this branch. Is there any firmware for the 5th hardware version radio?
>
Not yet : I need in the original firmware to make a mod. Maybe [huzheyi](https://github.com/huzheyi), who opened the issue, will be able to extract it. You also can help :
> > You will need in soldering iron, any USB-UART adapter with 3.3v output, PC with terminal software (I suggest Tera Term : https://ttssh2.osdn.jp/index.html.en)... and the right hands :). Are you ready?
> 


> Or is there any way to make it at least English?
> 
This method is for Mi walkie-talkie 2 model MJDJJ02FY, maybe it will work for your radio too:
Press the left walkie-talkie button - enter menu
Press the "^" button - move to the last menu item
You need 3d item from bottom, with the gear icon, select it with the left button 
Select the 4th item from top with the left button - time & language 
Then, select the 1st item from top - it is the language selection

**Comment by miheico** [comment]
> Not yet : I need in the original firmware to make a mod. Maybe [huzheyi](https://github.com/huzheyi), who opened the issue, will be able to extract it. You also can help :
> 
> > > You will need in soldering iron, any USB-UART adapter with 3.3v output, PC with terminal software (I suggest Tera Term : https://ttssh2.osdn.jp/index.html.en)... and the right hands :). Are you ready?

I would love to help. Where to buy the USB-UART and a microPC board? pls guide me with links.

**Comment by miheico** [comment]
and thx for the instruction for the English menu!!!!

**Comment by huzheyi** [comment]
I made a cable with PL2303 chip(I find you use a CH340 chip in the picture) and tried some baud rate like 9600, 115200, etc. I can get some outputs while cannot input. I'm not sure if this works properly, and I don't know what to do next. Below is the console.

![iShot2022-04-24_15 57 24](https://user-images.githubusercontent.com/8382132/164968746-ee12d9b3-2b7c-4bdc-ade8-30355b858a38.png)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> I made a cable with PL2303 chip(I find you use a CH340 chip in the picture) and tried some baud rate like 9600, 115200, etc. I can get some outputs while cannot input. I'm not sure if this works properly, and I don't know what to do next. Below is the console.
>
It is not a CH340 chip on my photo - it is FTDI FT232RL, but it does not matter : any adapter should work.
Correct serial port parameters are : 115200,  8bit, parity: none, stop bits: 1bit, flow control: none.

Do you have a Windows PC handy? The thing is, to download the walkie-talkie flash, I wrote a small script for Tera Term terminal app (it is an open-source app, https://ttssh2.osdn.jp/index.html.en) , but this app is available for Windows only.
To use Tera Term with the walkie-talkie, you should set serial port parameters as follows:
![TT_Setup_COM](https://user-images.githubusercontent.com/57772603/165092977-214d3436-371a-458d-8146-1146732bd746.png)

and the terminal parameters as follows:
![TT_Setup_Terminal](https://user-images.githubusercontent.com/57772603/165093197-8e91c71b-12ca-4c05-a8f4-210998d4ac41.png)

In case everything is correct, on connection you will see the walkie-talkie prompt like this:

**adc_sample = 3033,adc_volatge = 2427**
(number values could be different, of course)
Actually, it's a password prompt!

**Comment by huzheyi** [comment]
Thank you for your reply.
I made a mistake. The adapter I used is a USB-RS232 adapter indeed, there is another chip before PL2303 to change the electronic level. Thus I made a new cable with a CH340 chip, and now it works. 
![iShot_2022-04-26_12 05 28](https://user-images.githubusercontent.com/8382132/165218958-f5d667ae-2c9e-42cf-ad55-3f165902f997.png)
I've got ready to follow your next step to dump the firmware. Btw, I also get a PC handy.

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> I made a mistake. The adapter I used is a USB-RS232 adapter indeed, there is another chip before PL2303 to change the electronic level. Thus I made a new cable with a CH340 chip, and now it works.
>
Congratulations! You're very lucky you have not damaged your walkie-talkie with the wrong UART voltage!

Now, you need a Windows PC. Download the archive with my walkie-talkie flash dump TeraTerm script, and unpack "mi2_flash_dump.ttl" from it : [mi2_flash_dump.zip](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/files/9289911/mi2_flash_dump.zip). Connect USB-UART adapter to PC, install USB-UART drivers, install TeraTerm (from https://osdn.net/projects/ttssh2/releases/), and configure TeraTerm according to my previous post; pay attension you set "New Line" to "LF" both for receiving and transmit - it's important. Then, configure TeraTerm to log all the data exchange to file by clicking "File" -> "Log..." in TeraTerm menu and selecting the log file you want; clear "Append" checkmark in the log file options.

Connect your walkie-talkie to USB-UART adapter; you should see the walkie-talkie prompt "adc_sample = ****,adc_volatge = ****" in TeraTerm console window. Select "Control" -> "Macro" in TeraTerm menu, and select my "mi2_flash_dump.ttl" you've unpacked before - the script will run immediately, and you will see the data exhange in TeraTerm console window. Process will be long : 15 minutes or more; wait! When all the flash will be dumped, the script will show you message "Flash read completed" and stop. Now, close TeraTerm and send me the log file you have configured in "File" -> "Log..." before; I will be able to reconstruct the walkie-talkie firmware from this dump.

**Comment by huzheyi** [comment]
My device response command with a 'Success' instead of 'Success!'. What's more, during executing the macro it got timeout several times(maybe the cable is not that stable). I had to modify the address start position, rerun the macro, and edit the log file manully...

Finally, I got this done successfully. Here a upload the log file.

(Btw, Tera Term is an excellent tool. I'm looking for such a terminal app on MacOS which supports macro.)

[teraterm.zip](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/files/8570936/teraterm.zip)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> My device response command with a 'Success' instead of 'Success!'.
> 
My bad! I've forgotten that "mi2_flash_dump" macro was written to communicate the walkie-talkie in bootloader mode, so expected command responces are different.

> Finally, I got this done successfully. Here a upload the log file.
> 
Excellent! 👍 
I've reconstructed the walkie-talkie firmware file for hardware version 4.5 from the log you sent, and added it to the project. This firmware is nearly identical to the firmware for hardware version 4.8 (there are only 14 bytes different), so I was able to apply frequency range extension patch in binary form without disassembling; patched firmware file also added to the project.
Also, I've updated the original post on xda-developers https://forum.xda-developers.com/t/hack-xiaomi-mijia-walkie-talkie.3840164/post-86748839 with the new firmware mod archive url.
Updated Mi Walkie-Talkie 2 firmware mod archive is available here: https://drive.google.com/file/d/18RmIDL6monotCpcuPhwNW1LRabE0ZWh6 , try to flash it to your walkie-talkie with MiPTT+ !

**Comment by huzheyi** [comment]
Thank you for your work. I flashed this new mod to my walkie-talkie successfully. But there seems no difference to the original one, the limitation is still there when I try to edit the channel frequency.
![IMG_2127](https://user-images.githubusercontent.com/8382132/165709294-073a48ab-ffda-44aa-9150-23923d343011.jpg)
![IMG_2128](https://user-images.githubusercontent.com/8382132/165709319-608f3076-d53d-4bf9-b79f-be5693f5e62d.jpg)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> I flashed this new mod to my walkie-talkie successfully. But there seems no difference to the original one, the limitation is still there when I try to edit the channel frequency.
>
It's OK, I've mentioned this before on xda-developers. My firmware mod allows to use extended frequency range for channels **programmed from MiPTT+**, but it does not allow to set such a frequencies using the walkie-talkie internal editor.

Without the firmware mod, you also can create custom channel with a "disallowed" frequency from MiPTT+, and select such a channel - as a result, you will even see the desired frequency on the walkie-talkie display, but in fact, the walkie-talkie **will not operate** on this frequency due to firmware limitations!

Maybe, one day there will be a proficient reverse-engeneer who fix the walkie-talkie internal editor - but for me, it seems to be too much...

**Comment by huzheyi** [comment]
Okay, I understand. So it means, if I use MiPTT+ to program a channel (ig. 400MHz) with the orginal firmware, it'll dispaly '400MHz' in walkie-talkie while indeed it's not running on this frequency, right?

I've got an app before which is also a mod of ofiicial apk, it allows to set frequency 144-148 and 400-470. And there's no need to modify the firmware. But I didn't test if the walkie-talkie is actually work on that frequency or not. I'll upload the apk 
 [here](https://mega.nz/file/RIdySZJJ#c6HTNeW3KQNmgX3fTbz2OEFBmYtGZQrZj5yC8OIuJnQ) for you or others who are intrested in this for research.
![WechatIMG4](https://user-images.githubusercontent.com/8382132/165903991-4e637072-9270-42a0-ba39-fc08d53d34b3.jpeg)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> Okay, I understand. So it means, if I use MiPTT+ to program a channel (ig. 400MHz) with the orginal firmware, it'll dispaly '400MHz' in walkie-talkie while indeed it's not running on this frequency, right?
>
It is exactly right for disallowed frequencies, but 400MHz is in allowed range in the original firmware too. 
The code will be better than a thousand words - here is a decompiled pseudocode from the original (not patched) shark_1.0.5_hw8.idb firmware : 
```
int __fastcall set_1846_frequency(int a1)
{
  int result; // r0

  result = check_frequency_range(a1);
  if ( result < 2 )
    result = write_1846_frequency(dword_20000428[result] + a1);
  return result;
}

int __fastcall check_frequency_range(int a1)
{
  if ( (unsigned int)(a1 - 400000000) < 9750000 || (unsigned int)(a1 - 409987501) <= 60012499 )
    return 0;
  if ( (unsigned int)(a1 - 409750000) <= 237500 )
    return 0;
  if ( (unsigned int)(a1 - 144000000) > 4000000 )
    return 2;
  return 1;
}
```

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
With the help of [huzheyi](https://github.com/huzheyi), who dumped the original firmware of XMDJJ02 hardware version 4.5, the problem has been solved. 
Firmware files for hardware version 4.5 are added to the project tree, updated Mi Walkie-Talkie 2 firmware mod archive to flash with MiPTT+ is available here: https://drive.google.com/file/d/18RmIDL6monotCpcuPhwNW1LRabE0ZWh6 .

**Comment by huzheyi** [comment]
Bravo!

**Comment by magotpie** [comment]
what am i doing wrong here?
Nothing is showing at the terminal
![20220802_143749](https://user-images.githubusercontent.com/110448608/182308734-545fae43-1e64-4028-aa89-01ebd6aacef3.jpg)
![1](https://user-images.githubusercontent.com/110448608/182309186-c5bf656c-d636-4735-a9b9-bc9c9ee3ad21.jpg)
![2](https://user-images.githubusercontent.com/110448608/182309064-eec9c37d-d215-4925-9cd6-e8f3a35493db.jpg)
10448608/182309055-078f5e1d-36b7-4881-9993-926ea02adc4b.jpg)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> what am i doing wrong here?
> Nothing is showing at the terminal

Hi,
I see you are using the LOL1n NodeMCU board. The problem is, according to the NodeMCU pinout (https://www.teachmemicro.com/nodemcu-pinout/), board RX/TX pins are connected to ESP8266 controller, not to FTDI232 chip, so you can not use this board as a USB-UART adapter.

Please, use any dedicated USB-UART adapter board; to check it is OK, make a "loopback" by connecting adapter's TX and RX pins - as a result, any character you've sent with terminal program, should be immediately received and printed in terminal window twice.

**Comment by magotpie** [comment]
Ty. will try again.
can i use this chip?
![3212b536cb7ce7a4a1a901533460086b](https://user-images.githubusercontent.com/110448608/182378093-33bae1e7-5af6-43f1-a1f6-154cc9eea86e.jpg)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> can i use this chip?

This board is looks like a USB-UART adapter you need, but the chip label on the photo is wiped out, so I can't give a 100% guarantee. Try it in TeraTerm with TX and RX pins connected together, according to my previous post.

**Comment by magotpie** [comment]
![1](https://user-images.githubusercontent.com/110448608/183644291-0c63e10e-73c2-496c-a371-3ee42ad19ebb.jpg)
Silabs CP2102 DCL00X 2108+ Chip
I've loopback the TX RX pins and this showed up when i typed TEST
![3](https://user-images.githubusercontent.com/110448608/183644657-a79bc8e1-fda8-45f6-a6cf-5eafb1db7e56.jpg)
however, when i plugged in the walkie talkie, nothing showed up and running the macro i get this
![4](https://user-images.githubusercontent.com/110448608/183645876-c4187037-6778-4c2b-a5fb-dedcbf3fa6ed.jpg)
What am i doing wrong again?

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> I've loopback the TX RX pins and this showed up when i typed TEST

According to loopback test, your adapter is OK.


> however, when i plugged in the walkie talkie, nothing showed up

Something is wrong : walkie-talkie should tell "adc_sample = ****,adc_volatge = ****" in terminal window on connection.
Let's check :
1. Is your walkie-talkie turned ON ?
2. Is your wire correct? Could you check with a multimeter, that "RxD" is _really_ connected to "D-" ?
3.  What's the adapter output voltage level? On your previous photo, there is a jumper to set output voltage as 5V or 3.3V, but your current adapter does not have one, so how to configure it? You should be careful : the walkie-talkie UART is not 5V tolerance, and could be easely damaged with a wrong voltage! 
4. Have you configured your COM6 in TeraTerm to 115200 / 8 / 1 ? Keep in mind, TeraTerm does not save the settings automatically, so you have to set port parameters every time on start (or click "Setup" --> "Save setup" once after configuring).

**Comment by magotpie** [comment]
![20220819_201143](https://user-images.githubusercontent.com/110448608/185615960-a720bf56-3361-4484-957b-6a5b791de31b.jpg)
My 3rd Chip and still does the same thing.
nothing is shown on the terminal after connecting.
I've confirmed the settings also and now I am at a deadend.
I've also even changed 2 usb wires.
Maybe Mii changed the hardware to avoid this hack from happening.

Any idea how to proceed?

**Comment by glebaksenov12** [comment]
[teraterm_all.zip](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/files/9913954/teraterm_all.zip)

Hello. I have dumped 4.9. Here is the log file. Hope you can make the mod for it.

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> Hello. I have dumped 4.9. Here is the log file. Hope you can make the mod for it.

Thank you.
I've successfully reconstructed the original 4.9 firmware from your dump and added it to the project. Unfortunately, CPU code module for this hardware revision differs from 4.5/4.8 revisions (another build maybe?) , so it will take some time to make a mod.

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> Hello. I have dumped 4.9. Here is the log file. Hope you can make the mod for it.

Here is the modified firmware for 4.9 : [Mi2-nolimits-hw9.zip](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/files/10034082/Mi2-nolimits-hw9.zip).
Please, test the mod and let me know if it is OK, to include it to the next public update.

**Comment by glebaksenov12** [comment]
It worked. Thank you. Testing the functionality.
![изображение](https://user-images.githubusercontent.com/95185068/202799849-7c30d11f-d694-41fc-9e04-36a7846ab8c0.png)
![изображение](https://user-images.githubusercontent.com/95185068/202799889-afff832e-72c8-4e40-90e6-a8a45477776c.png)

**Comment by khoanguyen-3fc** [comment]
[teraterm_4.10.zip](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/files/12540690/teraterm_4.10.zip)

I've got a dump from v4.10, and also converted the SPI section into binary. But it doesn't look like a firmware (compared to hw9).

Any chance you could give me a quick guide on how to reconstruct the firmware?

<img width="1222" alt="image" src="https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/assets/16377833/3927649c-6a93-4d7a-a170-6f8a579cfbeb">

**Comment by khoanguyen-3fc** [comment]
I successfully figured out how to convert the dump to firmware, and applying the hex diff from v9 to v10 went smoothly. I also updated the header checksum with [fwinfo](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/fwinfo).

[shark_1.0.5_hw10.zip](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/files/12555315/shark_1.0.5_hw10.zip)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
Well done!

Your mod looks correctly, but unfortunately I can't test it because I don't have the XMDJJ02 radio.
Does it work?

**Comment by khoanguyen-3fc** [comment]
It worked!

Btw, I have a quick question, what's the purpose of the output of `flash read -chip`?

![](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/assets/16377833/bf690f06-4d9c-41b2-832d-48b20dbb9344)

**Comment by khoanguyen-3fc** [comment]
It worked!

Btw, I have a quick question, what's the purpose of the output of `flash read -chip`?

Also, what should I do if I accidentally brick my XMDJJ02 by flashing a bad firmware?

![](https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/assets/16377833/bf690f06-4d9c-41b2-832d-48b20dbb9344)

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> It worked!

Exellent!
Would you mind if I add your mod to the modded Mi2 firmware archive I've published on forum.xda-developers.com ?

> Btw, I have a quick question, what's the purpose of the output of `flash read -chip`?

The purpose is mainly historical : when I wrote the downloader script, I didn't know there is a copy of the CPU firmware block in the radio's external flash, so I dumped the CPU firmware from CPU flash directly by these commands. 
Also, there is a walki-talkie bootloader code block in the beginning of the CPU flash - it is worthy of study thing which is useful in case of accidentally bricking the radio.

> Also, what should I do if I accidentally brick my XMDJJ02 by flashing a bad firmware?

You can use bootloader mode: turn the radio off, press "PTT" and "-" buttons, then turn radio on while holding the buttons. There will be nothing on the screen, but you can connect radio to PC, enter the password (it is the same) and use console commands, as in the normal walkie-talkie operating mode - for example `flash write -chip ...`.

**Comment by khoanguyen-3fc** [comment]
> Would you mind if I add your mod to the modded Mi2 firmware archive I've published on forum.xda-developers.com ?

Absolutely! This is where it all started, your work is the core, and I've simply applied the hex diff. I'm really happy about giving back something to the community!
